//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="errorMessages" type="{http://npci.org/upi/schema/}errorMessage" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="api" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="reqMsgId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="err" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ts" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "errorMessages"
})
@XmlRootElement(name = "Ack")
public class Ack {

    protected List<ErrorMessage> errorMessages;
    @XmlAttribute
    protected String api;
    @XmlAttribute
    protected String reqMsgId;
    @XmlAttribute
    protected String err;
    @XmlAttribute
    protected String ts;

    /**
     * Gets the value of the errorMessages property.
     * <p/>
     * <p/>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the errorMessages property.
     * <p/>
     * <p/>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getErrorMessages().add(newItem);
     * </pre>
     * <p/>
     * <p/>
     * <p/>
     * Objects of the following type(s) are allowed in the list
     * {@link ErrorMessage }
     */
    public List<ErrorMessage> getErrorMessages() {
        if (errorMessages == null) {
            errorMessages = new ArrayList<ErrorMessage>();
        }
        return this.errorMessages;
    }

    /**
     * Gets the value of the api property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getApi() {
        return api;
    }

    /**
     * Sets the value of the api property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setApi(String value) {
        this.api = value;
    }

    /**
     * Gets the value of the reqMsgId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReqMsgId() {
        return reqMsgId;
    }

    /**
     * Sets the value of the reqMsgId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReqMsgId(String value) {
        this.reqMsgId = value;
    }

    /**
     * Gets the value of the err property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getErr() {
        return err;
    }

    /**
     * Sets the value of the err property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setErr(String value) {
        this.err = value;
    }

    /**
     * Gets the value of the ts property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTs(String value) {
        this.ts = value;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString(this);
    }
}
