//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for credType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="credType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AADHAAR"/>
 *     &lt;enumeration value="OTP"/>
 *     &lt;enumeration value="PIN"/>
 *     &lt;enumeration value="CARD"/>
 *     &lt;enumeration value="PreApproved"/>
 *     &lt;enumeration value="Challenge"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "credType")
@XmlEnum
public enum CredType {

    AADHAAR("AADHAAR"),
    OTP("OTP"),
    PIN("PIN"),
    CARD("CARD"),
    @XmlEnumValue("PreApproved")
    PRE_APPROVED("PreApproved"),
    @XmlEnumValue("Challenge")
    CHALLENGE("Challenge");
    private final String value;

    CredType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredType fromValue(String v) {
        for (CredType c: CredType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
