//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


/**
 * <p>Java class for headType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="headType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ver" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ts" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="orgId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="msgId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "headType")
public class HeadType {

    @XmlAttribute(required = true)
    protected String ver;
    @XmlAttribute(required = true)
    protected String ts;
    @XmlAttribute(required = true)
    protected String orgId;
    @XmlAttribute(required = true)
    protected String msgId;

    /**
     * Gets the value of the ver property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVer() {
        return ver;
    }

    /**
     * Sets the value of the ver property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVer(String value) {
        this.ver = value;
    }

    /**
     * Gets the value of the ts property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTs() {
        return ts;
    }

    /**
     * Sets the value of the ts property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTs(String value) {
        this.ts = value;
    }

    /**
     * Gets the value of the orgId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOrgId() {
        return orgId;
    }

    /**
     * Sets the value of the orgId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrgId(String value) {
        this.orgId = value;
    }

    /**
     * Gets the value of the msgId property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMsgId(String value) {
        this.msgId = value;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString(this);
    }
}
