//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


/**
 * <p>Java class for identityType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="identityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required" type="{http://npci.org/upi/schema/}identityConstant" />
 *       &lt;attribute name="verifiedName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identityType")
public class IdentityType {

    @XmlAttribute(required = true)
    protected IdentityConstant type;
    @XmlAttribute(required = true)
    protected String verifiedName;
    @XmlAttribute(required = true)
    protected String id;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link IdentityConstant }
     */
    public IdentityConstant getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link IdentityConstant }
     */
    public void setType(IdentityConstant value) {
        this.type = value;
    }

    /**
     * Gets the value of the verifiedName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVerifiedName() {
        return verifiedName;
    }

    /**
     * Sets the value of the verifiedName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVerifiedName(String value) {
        this.verifiedName = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setId(String value) {
        this.id = value;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString(this);
    }
}
