//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ultracash.upi.models package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ultracash.upi.models
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer.Bal }
     * 
     */
    public RespBalEnq.Payer.Bal createRespBalEnqPayerBal() {
        return new RespBalEnq.Payer.Bal();
    }

    /**
     * Create an instance of {@link PayeeType }
     * 
     */
    public PayeeType createPayeeType() {
        return new PayeeType();
    }

    /**
     * Create an instance of {@link PayeesType }
     * 
     */
    public PayeesType createPayeesType() {
        return new PayeesType();
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer.Bal.Data }
     * 
     */
    public RespBalEnq.Payer.Bal.Data createRespBalEnqPayerBalData() {
        return new RespBalEnq.Payer.Bal.Data();
    }

    /**
     * Create an instance of {@link RespListAccPvd }
     * 
     */
    public RespListAccPvd createRespListAccPvd() {
        return new RespListAccPvd();
    }

    /**
     * Create an instance of {@link ReqListKeys }
     * 
     */
    public ReqListKeys createReqListKeys() {
        return new ReqListKeys();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link RespPay }
     * 
     */
    public RespPay createRespPay() {
        return new RespPay();
    }

    /**
     * Create an instance of {@link CredsAllowedType }
     * 
     */
    public CredsAllowedType createCredsAllowedType() {
        return new CredsAllowedType();
    }

    /**
     * Create an instance of {@link RulesType }
     * 
     */
    public RulesType createRulesType() {
        return new RulesType();
    }

    /**
     * Create an instance of {@link RespChkTxn }
     * 
     */
    public RespChkTxn createRespChkTxn() {
        return new RespChkTxn();
    }

    /**
     * Create an instance of {@link RespPendingMsg.RespMsg }
     * 
     */
    public RespPendingMsg.RespMsg createRespPendingMsgRespMsg() {
        return new RespPendingMsg.RespMsg();
    }

    /**
     * Create an instance of {@link ReqRegMob.RegDetails }
     * 
     */
    public ReqRegMob.RegDetails createReqRegMobRegDetails() {
        return new ReqRegMob.RegDetails();
    }

    /**
     * Create an instance of {@link RespListAccPvd.AccPvdList.AccPvd }
     * 
     */
    public RespListAccPvd.AccPvdList.AccPvd createRespListAccPvdAccPvdListAccPvd() {
        return new RespListAccPvd.AccPvdList.AccPvd();
    }

    /**
     * Create an instance of {@link AccountType.Detail }
     * 
     */
    public AccountType.Detail createAccountTypeDetail() {
        return new AccountType.Detail();
    }

    /**
     * Create an instance of {@link RespListKeys }
     * 
     */
    public RespListKeys createRespListKeys() {
        return new RespListKeys();
    }

    /**
     * Create an instance of {@link ReqListVae }
     * 
     */
    public ReqListVae createReqListVae() {
        return new ReqListVae();
    }

    /**
     * Create an instance of {@link TxnConfDtl }
     * 
     */
    public TxnConfDtl createTxnConfDtl() {
        return new TxnConfDtl();
    }

    /**
     * Create an instance of {@link DeviceType.Tag }
     * 
     */
    public DeviceType.Tag createDeviceTypeTag() {
        return new DeviceType.Tag();
    }

    /**
     * Create an instance of {@link ReqRegMob }
     * 
     */
    public ReqRegMob createReqRegMob() {
        return new ReqRegMob();
    }

    /**
     * Create an instance of {@link CredsType.Cred.Data }
     * 
     */
    public CredsType.Cred.Data createCredsTypeCredData() {
        return new CredsType.Cred.Data();
    }

    /**
     * Create an instance of {@link RespHbt }
     * 
     */
    public RespHbt createRespHbt() {
        return new RespHbt();
    }

    /**
     * Create an instance of {@link RespType }
     * 
     */
    public RespType createRespType() {
        return new RespType();
    }

    /**
     * Create an instance of {@link PayTrans }
     * 
     */
    public PayTrans createPayTrans() {
        return new PayTrans();
    }

    /**
     * Create an instance of {@link ReqRegMob.RegDetails.Detail }
     * 
     */
    public ReqRegMob.RegDetails.Detail createReqRegMobRegDetailsDetail() {
        return new ReqRegMob.RegDetails.Detail();
    }

    /**
     * Create an instance of {@link RespBalEnq.Payer }
     * 
     */
    public RespBalEnq.Payer createRespBalEnqPayer() {
        return new RespBalEnq.Payer();
    }

    /**
     * Create an instance of {@link ReqOtp }
     * 
     */
    public ReqOtp createReqOtp() {
        return new ReqOtp();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link ReqValAdd }
     * 
     */
    public ReqValAdd createReqValAdd() {
        return new ReqValAdd();
    }

    /**
     * Create an instance of {@link ReqBalEnq }
     * 
     */
    public ReqBalEnq createReqBalEnq() {
        return new ReqBalEnq();
    }

    /**
     * Create an instance of {@link InfoType }
     * 
     */
    public InfoType createInfoType() {
        return new InfoType();
    }

    /**
     * Create an instance of {@link RespTxnConfirmation }
     * 
     */
    public RespTxnConfirmation createRespTxnConfirmation() {
        return new RespTxnConfirmation();
    }

    /**
     * Create an instance of {@link RespListKeys.KeyList.Key }
     * 
     */
    public RespListKeys.KeyList.Key createRespListKeysKeyListKey() {
        return new RespListKeys.KeyList.Key();
    }

    /**
     * Create an instance of {@link RespListPsp }
     * 
     */
    public RespListPsp createRespListPsp() {
        return new RespListPsp();
    }

    /**
     * Create an instance of {@link CredsType.Cred }
     * 
     */
    public CredsType.Cred createCredsTypeCred() {
        return new CredsType.Cred();
    }

    /**
     * Create an instance of {@link ReqHbt }
     * 
     */
    public ReqHbt createReqHbt() {
        return new ReqHbt();
    }

    /**
     * Create an instance of {@link ReqListAccount }
     * 
     */
    public ReqListAccount createReqListAccount() {
        return new ReqListAccount();
    }

    /**
     * Create an instance of {@link RespListAccount.AccountList }
     * 
     */
    public RespListAccount.AccountList createRespListAccountAccountList() {
        return new RespListAccount.AccountList();
    }

    /**
     * Create an instance of {@link PayerType }
     * 
     */
    public PayerType createPayerType() {
        return new PayerType();
    }

    /**
     * Create an instance of {@link RespListVae }
     * 
     */
    public RespListVae createRespListVae() {
        return new RespListVae();
    }

    /**
     * Create an instance of {@link ReqTxnConfirmation }
     * 
     */
    public ReqTxnConfirmation createReqTxnConfirmation() {
        return new ReqTxnConfirmation();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link CredsType.Cred.Hmac }
     * 
     */
    public CredsType.Cred.Hmac createCredsTypeCredHmac() {
        return new CredsType.Cred.Hmac();
    }

    /**
     * Create an instance of {@link RulesType.Rule }
     * 
     */
    public RulesType.Rule createRulesTypeRule() {
        return new RulesType.Rule();
    }

    /**
     * Create an instance of {@link ReqPay }
     * 
     */
    public ReqPay createReqPay() {
        return new ReqPay();
    }

    /**
     * Create an instance of {@link ReqManageVae }
     * 
     */
    public ReqManageVae createReqManageVae() {
        return new ReqManageVae();
    }

    /**
     * Create an instance of {@link RespListKeys.KeyList }
     * 
     */
    public RespListKeys.KeyList createRespListKeysKeyList() {
        return new RespListKeys.KeyList();
    }

    /**
     * Create an instance of {@link RespBalEnq }
     * 
     */
    public RespBalEnq createRespBalEnq() {
        return new RespBalEnq();
    }

    /**
     * Create an instance of {@link ReqManageVae.VaeList.Vae }
     * 
     */
    public ReqManageVae.VaeList.Vae createReqManageVaeVaeListVae() {
        return new ReqManageVae.VaeList.Vae();
    }

    /**
     * Create an instance of {@link RespRegMob }
     * 
     */
    public RespRegMob createRespRegMob() {
        return new RespRegMob();
    }

    /**
     * Create an instance of {@link ReqManageVae.VaeList }
     * 
     */
    public ReqManageVae.VaeList createReqManageVaeVaeList() {
        return new ReqManageVae.VaeList();
    }

    /**
     * Create an instance of {@link AccountType }
     * 
     */
    public AccountType createAccountType() {
        return new AccountType();
    }

    /**
     * Create an instance of {@link CredsType }
     * 
     */
    public CredsType createCredsType() {
        return new CredsType();
    }

    /**
     * Create an instance of {@link ReqPendingMsg.ReqMsg }
     * 
     */
    public ReqPendingMsg.ReqMsg createReqPendingMsgReqMsg() {
        return new ReqPendingMsg.ReqMsg();
    }

    /**
     * Create an instance of {@link DeviceType }
     * 
     */
    public DeviceType createDeviceType() {
        return new DeviceType();
    }

    /**
     * Create an instance of {@link RiskScoresType.Score }
     * 
     */
    public RiskScoresType.Score createRiskScoresTypeScore() {
        return new RiskScoresType.Score();
    }

    /**
     * Create an instance of {@link CredsType.Cred.Skey }
     * 
     */
    public CredsType.Cred.Skey createCredsTypeCredSkey() {
        return new CredsType.Cred.Skey();
    }

    /**
     * Create an instance of {@link AmountType.Split }
     * 
     */
    public AmountType.Split createAmountTypeSplit() {
        return new AmountType.Split();
    }

    /**
     * Create an instance of {@link ReqHbt.HbtMsg }
     * 
     */
    public ReqHbt.HbtMsg createReqHbtHbtMsg() {
        return new ReqHbt.HbtMsg();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link ReqListAccount.Link }
     * 
     */
    public ReqListAccount.Link createReqListAccountLink() {
        return new ReqListAccount.Link();
    }

    /**
     * Create an instance of {@link RespSetCre }
     * 
     */
    public RespSetCre createRespSetCre() {
        return new RespSetCre();
    }

    /**
     * Create an instance of {@link ReqChkTxn }
     * 
     */
    public ReqChkTxn createReqChkTxn() {
        return new ReqChkTxn();
    }

    /**
     * Create an instance of {@link RespListVae.VaeList.Vae }
     * 
     */
    public RespListVae.VaeList.Vae createRespListVaeVaeListVae() {
        return new RespListVae.VaeList.Vae();
    }

    /**
     * Create an instance of {@link RespListAccount.AccountList.Account }
     * 
     */
    public RespListAccount.AccountList.Account createRespListAccountAccountListAccount() {
        return new RespListAccount.AccountList.Account();
    }

    /**
     * Create an instance of {@link RiskScoresType }
     * 
     */
    public RiskScoresType createRiskScoresType() {
        return new RiskScoresType();
    }

    /**
     * Create an instance of {@link RespListVae.VaeList }
     * 
     */
    public RespListVae.VaeList createRespListVaeVaeList() {
        return new RespListVae.VaeList();
    }

    /**
     * Create an instance of {@link ReqPay.Meta }
     * 
     */
    public ReqPay.Meta createReqPayMeta() {
        return new ReqPay.Meta();
    }

    /**
     * Create an instance of {@link RespAuthDetails }
     * 
     */
    public RespAuthDetails createRespAuthDetails() {
        return new RespAuthDetails();
    }

    /**
     * Create an instance of {@link AmountType }
     * 
     */
    public AmountType createAmountType() {
        return new AmountType();
    }

    /**
     * Create an instance of {@link RespOtp }
     * 
     */
    public RespOtp createRespOtp() {
        return new RespOtp();
    }

    /**
     * Create an instance of {@link ReqAuthDetails }
     * 
     */
    public ReqAuthDetails createReqAuthDetails() {
        return new ReqAuthDetails();
    }

    /**
     * Create an instance of {@link RespPendingMsg }
     * 
     */
    public RespPendingMsg createRespPendingMsg() {
        return new RespPendingMsg();
    }

    /**
     * Create an instance of {@link ReqListAccPvd }
     * 
     */
    public ReqListAccPvd createReqListAccPvd() {
        return new ReqListAccPvd();
    }

    /**
     * Create an instance of {@link RespListAccPvd.AccPvdList }
     * 
     */
    public RespListAccPvd.AccPvdList createRespListAccPvdAccPvdList() {
        return new RespListAccPvd.AccPvdList();
    }

    /**
     * Create an instance of {@link Ref }
     * 
     */
    public Ref createRef() {
        return new Ref();
    }

    /**
     * Create an instance of {@link ReqPendingMsg }
     * 
     */
    public ReqPendingMsg createReqPendingMsg() {
        return new ReqPendingMsg();
    }

    /**
     * Create an instance of {@link ReqSetCre }
     * 
     */
    public ReqSetCre createReqSetCre() {
        return new ReqSetCre();
    }

    /**
     * Create an instance of {@link RespManageVae }
     * 
     */
    public RespManageVae createRespManageVae() {
        return new RespManageVae();
    }

    /**
     * Create an instance of {@link RespListPsp.PspList }
     * 
     */
    public RespListPsp.PspList createRespListPspPspList() {
        return new RespListPsp.PspList();
    }

    /**
     * Create an instance of {@link ReqPay.Meta.Tag }
     * 
     */
    public ReqPay.Meta.Tag createReqPayMetaTag() {
        return new ReqPay.Meta.Tag();
    }

    /**
     * Create an instance of {@link RespValAdd }
     * 
     */
    public RespValAdd createRespValAdd() {
        return new RespValAdd();
    }

    /**
     * Create an instance of {@link ReqListPsp }
     * 
     */
    public ReqListPsp createReqListPsp() {
        return new ReqListPsp();
    }

    /**
     * Create an instance of {@link RespPay.Resp }
     * 
     */
    public RespPay.Resp createRespPayResp() {
        return new RespPay.Resp();
    }

    /**
     * Create an instance of {@link RespListPsp.PspList.Psp }
     * 
     */
    public RespListPsp.PspList.Psp createRespListPspPspListPsp() {
        return new RespListPsp.PspList.Psp();
    }

    /**
     * Create an instance of {@link RespListAccount }
     * 
     */
    public RespListAccount createRespListAccount() {
        return new RespListAccount();
    }

    /**
     * Create an instance of {@link Ack }
     * 
     */
    public Ack createAck() {
        return new Ack();
    }

    /**
     * Create an instance of {@link RespTypeValAddr }
     * 
     */
    public RespTypeValAddr createRespTypeValAddr() {
        return new RespTypeValAddr();
    }

}
