//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.04 at 04:26:32 PM GMT+05:30 
//
@XmlSchema(
        namespace = "http://npci.org/upi/schema/",
        xmlns = {
                @XmlNs(prefix = "upi", namespaceURI = "http://npci.org/upi/schema/")
        }
)

package com.ultracash.upi.models;

import javax.xml.bind.annotation.XmlNs;
import javax.xml.bind.annotation.XmlSchema;

