//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


/**
 * <p>Java class for payerType complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="payerType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Info" type="{http://npci.org/upi/schema/}infoType" minOccurs="0"/>
 *         &lt;element name="Device" type="{http://npci.org/upi/schema/}deviceType" minOccurs="0"/>
 *         &lt;element name="Ac" type="{http://npci.org/upi/schema/}accountType" minOccurs="0"/>
 *         &lt;element name="Creds" type="{http://npci.org/upi/schema/}credsType" minOccurs="0"/>
 *         &lt;element name="Amount" type="{http://npci.org/upi/schema/}amountType" minOccurs="0"/>
 *         &lt;element name="NewCred" type="{http://npci.org/upi/schema/}credsType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://npci.org/upi/schema/}payerConstant" />
 *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "payerType", propOrder = {
        "info",
        "device",
        "ac",
        "creds",
        "amount",
        "newCred"
})
public class PayerType {

    @XmlElement(name = "Info")
    protected InfoType info;
    @XmlElement(name = "Device")
    protected DeviceType device;
    @XmlElement(name = "Ac")
    protected AccountType ac;
    @XmlElement(name = "Creds")
    protected CredsType creds;
    @XmlElement(name = "Amount")
    protected AmountType amount;
    @XmlElement(name = "NewCred")
    protected CredsType newCred;
    @XmlAttribute
    protected String addr;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String seqNum;
    @XmlAttribute
    protected PayerConstant type;
    @XmlAttribute
    protected String code;

    /**
     * Gets the value of the info property.
     *
     * @return possible object is
     * {@link InfoType }
     */
    public InfoType getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     *
     * @param value allowed object is
     *              {@link InfoType }
     */
    public void setInfo(InfoType value) {
        this.info = value;
    }

    /**
     * Gets the value of the device property.
     *
     * @return possible object is
     * {@link DeviceType }
     */
    public DeviceType getDevice() {
        return device;
    }

    /**
     * Sets the value of the device property.
     *
     * @param value allowed object is
     *              {@link DeviceType }
     */
    public void setDevice(DeviceType value) {
        this.device = value;
    }

    /**
     * Gets the value of the ac property.
     *
     * @return possible object is
     * {@link AccountType }
     */
    public AccountType getAc() {
        return ac;
    }

    /**
     * Sets the value of the ac property.
     *
     * @param value allowed object is
     *              {@link AccountType }
     */
    public void setAc(AccountType value) {
        this.ac = value;
    }

    /**
     * Gets the value of the creds property.
     *
     * @return possible object is
     * {@link CredsType }
     */
    public CredsType getCreds() {
        return creds;
    }

    /**
     * Sets the value of the creds property.
     *
     * @param value allowed object is
     *              {@link CredsType }
     */
    public void setCreds(CredsType value) {
        this.creds = value;
    }

    /**
     * Gets the value of the amount property.
     *
     * @return possible object is
     * {@link AmountType }
     */
    public AmountType getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value allowed object is
     *              {@link AmountType }
     */
    public void setAmount(AmountType value) {
        this.amount = value;
    }

    /**
     * Gets the value of the newCred property.
     *
     * @return possible object is
     * {@link CredsType }
     */
    public CredsType getNewCred() {
        return newCred;
    }

    /**
     * Sets the value of the newCred property.
     *
     * @param value allowed object is
     *              {@link CredsType }
     */
    public void setNewCred(CredsType value) {
        this.newCred = value;
    }

    /**
     * Gets the value of the addr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the seqNum property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSeqNum(String value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link PayerConstant }
     */
    public PayerConstant getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link PayerConstant }
     */
    public void setType(PayerConstant value) {
        this.type = value;
    }

    /**
     * Gets the value of the code property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getCode() {
        return code;
    }

    /**
     * Sets the value of the code property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setCode(String value) {
        this.code = value;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString(this);
    }
}
