//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


/**
 * <p>Java class for ref complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="ref">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" type="{http://npci.org/upi/schema/}refType" />
 *       &lt;attribute name="seqNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="addr" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settAmount" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="settCurrency" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="approvalNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="respCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="regName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ref")
public class Ref {

    @XmlAttribute
    protected RefType type;
    @XmlAttribute
    protected String seqNum;
    @XmlAttribute
    protected String addr;
    @XmlAttribute
    protected String settAmount;
    @XmlAttribute
    protected String settCurrency;
    @XmlAttribute
    protected String approvalNum;
    @XmlAttribute
    protected String respCode;
    @XmlAttribute
    protected String regName;

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link RefType }
     */
    public RefType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link RefType }
     */
    public void setType(RefType value) {
        this.type = value;
    }

    /**
     * Gets the value of the seqNum property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSeqNum() {
        return seqNum;
    }

    /**
     * Sets the value of the seqNum property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSeqNum(String value) {
        this.seqNum = value;
    }

    /**
     * Gets the value of the addr property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getAddr() {
        return addr;
    }

    /**
     * Sets the value of the addr property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setAddr(String value) {
        this.addr = value;
    }

    /**
     * Gets the value of the settAmount property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSettAmount() {
        return settAmount;
    }

    /**
     * Sets the value of the settAmount property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSettAmount(String value) {
        this.settAmount = value;
    }

    /**
     * Gets the value of the settCurrency property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getSettCurrency() {
        return settCurrency;
    }

    /**
     * Sets the value of the settCurrency property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setSettCurrency(String value) {
        this.settCurrency = value;
    }

    /**
     * Gets the value of the approvalNum property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getApprovalNum() {
        return approvalNum;
    }

    /**
     * Sets the value of the approvalNum property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setApprovalNum(String value) {
        this.approvalNum = value;
    }

    /**
     * Gets the value of the respCode property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRespCode() {
        return respCode;
    }

    /**
     * Sets the value of the respCode property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRespCode(String value) {
        this.respCode = value;
    }

    /**
     * Gets the value of the regName property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getRegName() {
        return regName;
    }

    /**
     * Sets the value of the regName property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRegName(String value) {
        this.regName = value;
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString(this);
    }
}
