//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Head" type="{http://npci.org/upi/schema/}headType"/>
 *         &lt;element name="Txn" type="{http://npci.org/upi/schema/}payTrans"/>
 *         &lt;element name="Resp">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Ref" type="{http://npci.org/upi/schema/}ref" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="reqMsgId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="result" type="{http://npci.org/upi/schema/}resultType" />
 *                 &lt;attribute name="errCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="approvalNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "head",
        "txn",
        "resp"
})
@XmlRootElement(name = "RespPay")
public class RespPay {

    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Txn", required = true)
    protected PayTrans txn;
    @XmlElement(name = "Resp", required = true)
    protected RespPay.Resp resp;

    /**
     * Gets the value of the head property.
     *
     * @return possible object is
     * {@link HeadType }
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     *
     * @param value allowed object is
     *              {@link HeadType }
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the txn property.
     *
     * @return possible object is
     * {@link PayTrans }
     */
    public PayTrans getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     *
     * @param value allowed object is
     *              {@link PayTrans }
     */
    public void setTxn(PayTrans value) {
        this.txn = value;
    }

    /**
     * Gets the value of the resp property.
     *
     * @return possible object is
     * {@link RespPay.Resp }
     */
    public RespPay.Resp getResp() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     *
     * @param value allowed object is
     *              {@link RespPay.Resp }
     */
    public void setResp(RespPay.Resp value) {
        this.resp = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Ref" type="{http://npci.org/upi/schema/}ref" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="reqMsgId" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="result" type="{http://npci.org/upi/schema/}resultType" />
     *       &lt;attribute name="errCode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="approvalNum" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "ref"
    })
    public static class Resp {

        @XmlElement(name = "Ref")
        protected List<Ref> ref;
        @XmlAttribute
        protected String reqMsgId;
        @XmlAttribute
        protected ResultType result;
        @XmlAttribute
        protected String errCode;
        @XmlAttribute
        protected String approvalNum;

        /**
         * Gets the value of the ref property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ref property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRef().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link Ref }
         */
        public List<Ref> getRef() {
            if (ref == null) {
                ref = new ArrayList<Ref>();
            }
            return this.ref;
        }

        /**
         * Gets the value of the reqMsgId property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getReqMsgId() {
            return reqMsgId;
        }

        /**
         * Sets the value of the reqMsgId property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setReqMsgId(String value) {
            this.reqMsgId = value;
        }

        /**
         * Gets the value of the result property.
         *
         * @return possible object is
         * {@link ResultType }
         */
        public ResultType getResult() {
            return result;
        }

        /**
         * Sets the value of the result property.
         *
         * @param value allowed object is
         *              {@link ResultType }
         */
        public void setResult(ResultType value) {
            this.result = value;
        }

        /**
         * Gets the value of the errCode property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getErrCode() {
            return errCode;
        }

        /**
         * Sets the value of the errCode property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setErrCode(String value) {
            this.errCode = value;
        }

        /**
         * Gets the value of the approvalNum property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getApprovalNum() {
            return approvalNum;
        }

        /**
         * Sets the value of the approvalNum property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setApprovalNum(String value) {
            this.approvalNum = value;
        }

        @Override
        public String toString() {
            return ReflectionToStringBuilder.reflectionToString(this);
        }
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString(this);
    }
}
