//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 06:38:41 PM GMT+05:30 
//


package com.ultracash.upi.models;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Head" type="{http://npci.org/upi/schema/}headType"/>
 *         &lt;element name="Resp" type="{http://npci.org/upi/schema/}respType"/>
 *         &lt;element name="Txn" type="{http://npci.org/upi/schema/}payTrans"/>
 *         &lt;element name="AccPvdList">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="AccPvd" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="iin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="active" type="{http://npci.org/upi/schema/}activeType" />
 *                           &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="spocName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="spocEmail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="spocPhone" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="prods" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="lastModifedTs" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "head",
        "resp",
        "txn",
        "accPvdList"
})
@XmlRootElement(name = "RespListAccPvd")
public class RespListAccPvd {

    @XmlElement(name = "Head", required = true)
    protected HeadType head;
    @XmlElement(name = "Resp", required = true)
    protected RespType resp;
    @XmlElement(name = "Txn", required = true)
    protected PayTrans txn;
    @XmlElement(name = "AccPvdList", required = true)
    protected RespListAccPvd.AccPvdList accPvdList;

    /**
     * Gets the value of the head property.
     *
     * @return possible object is
     * {@link HeadType }
     */
    public HeadType getHead() {
        return head;
    }

    /**
     * Sets the value of the head property.
     *
     * @param value allowed object is
     *              {@link HeadType }
     */
    public void setHead(HeadType value) {
        this.head = value;
    }

    /**
     * Gets the value of the resp property.
     *
     * @return possible object is
     * {@link RespType }
     */
    public RespType getResp() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     *
     * @param value allowed object is
     *              {@link RespType }
     */
    public void setResp(RespType value) {
        this.resp = value;
    }

    /**
     * Gets the value of the txn property.
     *
     * @return possible object is
     * {@link PayTrans }
     */
    public PayTrans getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     *
     * @param value allowed object is
     *              {@link PayTrans }
     */
    public void setTxn(PayTrans value) {
        this.txn = value;
    }

    /**
     * Gets the value of the accPvdList property.
     *
     * @return possible object is
     * {@link RespListAccPvd.AccPvdList }
     */
    public RespListAccPvd.AccPvdList getAccPvdList() {
        return accPvdList;
    }

    /**
     * Sets the value of the accPvdList property.
     *
     * @param value allowed object is
     *              {@link RespListAccPvd.AccPvdList }
     */
    public void setAccPvdList(RespListAccPvd.AccPvdList value) {
        this.accPvdList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * <p/>
     * <p>The following schema fragment specifies the expected content contained within this class.
     * <p/>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="AccPvd" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="iin" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="active" type="{http://npci.org/upi/schema/}activeType" />
     *                 &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="spocName" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="spocEmail" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="spocPhone" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="prods" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="lastModifedTs" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "accPvd"
    })
    public static class AccPvdList {

        @XmlElement(name = "AccPvd", required = true)
        protected List<RespListAccPvd.AccPvdList.AccPvd> accPvd;

        /**
         * Gets the value of the accPvd property.
         * <p/>
         * <p/>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the accPvd property.
         * <p/>
         * <p/>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccPvd().add(newItem);
         * </pre>
         * <p/>
         * <p/>
         * <p/>
         * Objects of the following type(s) are allowed in the list
         * {@link RespListAccPvd.AccPvdList.AccPvd }
         */
        public List<RespListAccPvd.AccPvdList.AccPvd> getAccPvd() {
            if (accPvd == null) {
                accPvd = new ArrayList<RespListAccPvd.AccPvdList.AccPvd>();
            }
            return this.accPvd;
        }


        /**
         * <p>Java class for anonymous complex type.
         * <p/>
         * <p>The following schema fragment specifies the expected content contained within this class.
         * <p/>
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="iin" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="active" type="{http://npci.org/upi/schema/}activeType" />
         *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="spocName" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="spocEmail" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="spocPhone" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="prods" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="lastModifedTs" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "value"
        })
        public static class AccPvd {

            @XmlValue
            protected String value;
            @XmlAttribute
            protected String name;
            @XmlAttribute
            protected String iin;
            @XmlAttribute
            protected ActiveType active;
            @XmlAttribute
            protected String url;
            @XmlAttribute
            protected String spocName;
            @XmlAttribute
            protected String spocEmail;
            @XmlAttribute
            protected String spocPhone;
            @XmlAttribute
            protected String prods;
            @XmlAttribute
            protected String lastModifedTs;

            /**
             * Gets the value of the value property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the iin property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getIin() {
                return iin;
            }

            /**
             * Sets the value of the iin property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setIin(String value) {
                this.iin = value;
            }

            /**
             * Gets the value of the active property.
             *
             * @return possible object is
             * {@link ActiveType }
             */
            public ActiveType getActive() {
                return active;
            }

            /**
             * Sets the value of the active property.
             *
             * @param value allowed object is
             *              {@link ActiveType }
             */
            public void setActive(ActiveType value) {
                this.active = value;
            }

            /**
             * Gets the value of the url property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setUrl(String value) {
                this.url = value;
            }

            /**
             * Gets the value of the spocName property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getSpocName() {
                return spocName;
            }

            /**
             * Sets the value of the spocName property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setSpocName(String value) {
                this.spocName = value;
            }

            /**
             * Gets the value of the spocEmail property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getSpocEmail() {
                return spocEmail;
            }

            /**
             * Sets the value of the spocEmail property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setSpocEmail(String value) {
                this.spocEmail = value;
            }

            /**
             * Gets the value of the spocPhone property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getSpocPhone() {
                return spocPhone;
            }

            /**
             * Sets the value of the spocPhone property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setSpocPhone(String value) {
                this.spocPhone = value;
            }

            /**
             * Gets the value of the prods property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getProds() {
                return prods;
            }

            /**
             * Sets the value of the prods property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setProds(String value) {
                this.prods = value;
            }

            /**
             * Gets the value of the lastModifedTs property.
             *
             * @return possible object is
             * {@link String }
             */
            public String getLastModifedTs() {
                return lastModifedTs;
            }

            /**
             * Sets the value of the lastModifedTs property.
             *
             * @param value allowed object is
             *              {@link String }
             */
            public void setLastModifedTs(String value) {
                this.lastModifedTs = value;
            }

            @Override
            public String toString() {
                return ReflectionToStringBuilder.reflectionToString(this);
            }
        }

        @Override
        public String toString() {
            return ReflectionToStringBuilder.reflectionToString(this);
        }
    }

    @Override
    public String toString() {
        return ReflectionToStringBuilder.reflectionToString(this);
    }
}
